# Starter pipeline

# Define the build number format
name: $(Build.SourceBranchName)-$(Build.BuildId)

pool:
  name: 'praveen-self-hosted-agent'

jobs:
- job: Build
  steps:
  
  # Restore NuGet packages
  - task: DotNetCoreCLI@2
    inputs:
      azureSubscription: 'devops-demo-service-connection'
      command: 'restore'
      projects: '**/*.csproj'

  # Build the project
  - task: DotNetCoreCLI@2
    inputs:
      azureSubscription: 'devops-demo-service-connection'
      command: 'build'
      projects: '**/*.csproj'

  # Publish the project
  - task: DotNetCoreCLI@2
    inputs:
      azureSubscription: 'devops-demo-service-connection'
      command: 'publish'
      publishWebProjects: false
      projects: '**/*.csproj'
      zipAfterPublish: true
      arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'

  # Publish build artifacts
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'drop'
      publishLocation: 'Container'
