# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

# trigger:
# - main

pool:
  name: 'praveen-self-hosted-agent'

jobs:
- job: Build
  steps:
  - script: echo Hello, world!
    displayName: 'Run a one-line script'
  
  - task: DotNetCoreCLI@2
    inputs:
      azureSubscription: 'devops-demo-service-connection'
      command: 'build'
      projects: '**/*.csproj'
  
  - task: DotNetCoreCLI@2
    inputs:
      azureSubscription: 'devops-demo-service-connection'
      command: 'publish'
      publishWebProjects: false
      projects: '**/*.csproj'
      zipAfterPublish: true
      arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'drop'
      publishLocation: 'Container'




